# Generated by Django 3.0.5 on 2021-05-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporters',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=10)),
                ('bio', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('headline', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(default='desconhecido', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Reporters')),
            ],
        ),
    ]
