# Generated by Django 3.0.5 on 2021-06-26 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
                ('bio', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('headline', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='static/images/default.jpeg', upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
