# Generated by Django 3.0.5 on 2021-06-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='static/images/default.jpeg', upload_to='media/'),
        ),
    ]
