# Generated by Django 3.0.5 on 2021-05-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_articles_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporters',
            name='birthday',
            field=models.CharField(max_length=10),
        ),
    ]
