# Generated by Django 3.0.5 on 2021-05-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210523_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporters',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
