# Generated by Django 3.0.5 on 2021-05-23 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210523_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 23, 52, 18, 4906, tzinfo=utc)),
        ),
    ]
