# Generated by Django 3.0.5 on 2021-05-24 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210523_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
