# Generated by Django 3.0.5 on 2021-05-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_articles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
    ]
