# Generated by Django 3.0.5 on 2021-05-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='static/images/default.jpeg', upload_to='static/images'),
        ),
    ]
