# Generated by Django 3.0.5 on 2021-05-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='static/images/default.jpeg', upload_to=''),
        ),
    ]
